import { useAuth } from '../../context/AuthContext';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Card';
import { Avatar } from '../../components/ui/Avatar';
import { AdminPageHeader } from '../../components/admin/Parts';

export default function AdminSettings() {
  const { profile } = useAuth();

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <AdminPageHeader title="Settings" description="Club configuration and administrator identity." />

      <Card className="p-6 sm:p-8">
        <div className="flex items-center gap-4">
          <Avatar src={profile?.avatar_url} name={profile?.full_name} size={56} />
          <div>
            <h2 className="font-display text-lg">{profile?.full_name}</h2>
            <p className="text-sm text-silver-400">{profile?.email}</p>
            <div className="mt-2">
              <Badge status="active">Administrator</Badge>
            </div>
          </div>
        </div>
        <p className="mt-6 border-t border-white/[0.06] pt-6 text-xs leading-relaxed text-silver-500">
          Administrators are stored in the database with role <span className="font-mono text-gold-300">admin</span> on
          their profile. Every admin API call verifies that role server-side; the frontend never decides
          access. The initial administrator is created with <span className="font-mono">npm run seed</span>.
        </p>
      </Card>

      <Card className="p-6 sm:p-8">
        <h3 className="font-display text-base">Platform</h3>
        <dl className="mt-5 divide-y divide-white/[0.04]">
          {[
            ['Membership model', 'Application + admin approval. No payments.'],
            ['Member ID format', 'GC-YYYY-NNNNNN — generated by a Postgres sequence.'],
            ['Verification', 'QR deep-links to /verify/{member_id} and performs a live registry lookup.'],
            ['Storage', 'Supabase Storage — avatars and media buckets.'],
            ['Security', 'Row Level Security plus server-side role checks on every protected route.'],
          ].map(([k, v]) => (
            <div key={k} className="grid gap-1 py-3.5 sm:grid-cols-[180px_1fr] sm:gap-4">
              <dt className="font-mono text-2xs uppercase tracking-[0.2em] text-silver-500">{k}</dt>
              <dd className="text-sm text-silver-300">{v}</dd>
            </div>
          ))}
        </dl>
      </Card>
    </div>
  );
}
